### ISSUE TITLE
Vulkan API version is not verified?

### ISSUE THREAD

**Issue by ethan-tqa** [MaikKlein/ash#14]
In the ApplicationInfo struct, I can pass in a bogus API version, like `vk_make_version!(1,0,100)` and it still works, but `vk_make_version!(1,1,100)` will fail with ErrorIncompatibleDriver error. Both should fail in the same way.

**Comment by MaikKlein** [comment]
This is expected see

`apiVersion is the version of the Vulkan API against which the application expects to run, encoded as described in the API Version Numbers and Semantics section. If apiVersion is 0 the implementation must ignore it, otherwise if the implementation does not support the requested apiVersion it must return VK_ERROR_INCOMPATIBLE_DRIVER. The patch version number specified in apiVersion is ignored when creating an instance object. Only the major and minor versions of the instance must match those requested in apiVersion.`
