### ISSUE TITLE
SECURITY_ATTRIBUTES for windows is still not implemented

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#156]
```
typedef struct _SECURITY_ATTRIBUTES {
  DWORD  nLength;
  LPVOID lpSecurityDescriptor;
  BOOL   bInheritHandle;
} SECURITY_ATTRIBUTES, *PSECURITY_ATTRIBUTES, *LPSECURITY_ATTRIBUTES;
```
See https://github.com/MaikKlein/ash/blob/master/generator/src/lib.rs#L357-L360

Should we use a library for this? Or should we just implement it manually?

**Comment by Ralith** [comment]
winapi [defines this](https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/minwinbase/struct.SECURITY_ATTRIBUTES.html). Reusing the de-facto standard crate seems nice, unless anyone can think of any serious drawbacks.

**Comment by aloucks** [comment]
Adding the `winapi` dependency for a single struct definition seems like overkill. I would probably just implement it manually.

**Comment by MarijnS95** [comment]
With [`windows-rs`](https://github.com/microsoft/windows-rs/) we _could_ generate just the bindings for this type. Binding generation and compiling is crazy fast, but the Windows crate and generator itself are pretty slow to compile.

Then there's the obvious problem of crate incompatibility: crate users will have their own bindings which are type-incompatible despite carrying the same name and layout. Is there any reason this type is needed, do we have to access the fields from within Ash?

Otherwise we should probably keep all such pointers opaque types like `c_void` and leave it up to the caller to perform the pointer cast from their own type.

**Comment by Ralith** [comment]
I'm strongly in favor of an opaque pointer if it's sufficient.

**Comment by MarijnS95** [comment]
> Otherwise we should probably keep all such pointers opaque types like `c_void` and leave it up to the caller to perform the pointer cast from their own type.

As noted in https://github.com/ash-rs/ash/pull/950 this is not actually a _pointer_ to easily cast, but a mutable borrow - and this doesn't allow `NULL` values either even though the documentation suggests it should be valid.

Perhaps we should add it to the list of "opaque types" there to solve both issues?
