### ISSUE TITLE
empty slices don't always result in null pointers

### ISSUE THREAD

**Issue by remexre** [MaikKlein/ash#256]
Ran into this specifically for https://docs.rs/ash/0.29.0/ash/vk/struct.PipelineMultisampleStateCreateInfoBuilder.html#method.sample_mask -- if I pass a reference to an empty slice, `as_ptr` doesn't necessarily return `NULL`.

**Comment by Ralith** [comment]
Relevant section from the spec:

>  If pSampleMask is not NULL, pSampleMask must be a valid pointer to an array of ceil(rasterizationSamples/32) VkSampleMask values

Interesting case due to the implicit length. Not calling the method at all should work, but could be unergonomic. Special-casing zero lengths in general is possible, but maybe less zero-cost than ideal. Maybe only the cases where there's no associated array length variable?

**Comment by coffeenotfound** [comment]
The best solution would be taking Option<&'a [T]> where the Vulkan spec allows pointers to be null

**Comment by Ralith** [comment]
Specifically, that is appropriate if and only if there is an implicit length field *and* it's correct to combine a nonzero length with a null pointer. This is very rare; the overwhelming majority of the time, either you pass a length of zero and the pointer doesn't matter or the pointer must be nonnull.

**Comment by MarijnS95** [comment]
Is this still an issue in practice? This case seems rare enough that it won't hurt to have something along the lines of:

```rust
let mut builder = vk::PipelineMultisampleStateCreateInfo::builder()
    ...;

if blah {
    builder = builder.sample_mask(my_slice);
}
...
```

It wouldn't be too hard to change this though since `pSampleMask` is already special-cased:

https://github.com/MaikKlein/ash/blob/c7216f1c1e337f42572995c53ced178b41cf2dbe/generator/src/lib.rs#L1826-L1833

**Comment by coffeenotfound** [comment]
@MarijnS95 It definitely is a correctness issue and as a Rust dev im kinda past the point of finding them acceptable. I mean passing an empty slice happens. I've done it -- and ran into this exact problem. Shouldn't we kinda strive to build better APIs instead of turning a blind eye because "it probably doesn't _really_ happen all that often"?

**Comment by MarijnS95** [comment]
@coffeenotfound Feel free to submit a PR changing this to take an `Option` :+1:

**Comment by coffeenotfound** [comment]
@MarijnS95 Quite some time since I last did Vulkan 😅 If I remember correctly though there are only a handful of cases where the Vulkan API differentiates between (or even allows) null pointers and empty lists. So I guess it would only concern a few functions

I'd love to open a PR but right now I sadly don't have the time to work on my engine and Vulkan stuff

**Comment by MarijnS95** [comment]
@coffeenotfound it is fairly trivial to adjust this function as it was already overridden. Afaik it was overridden for this reason in the first place: the length of this array is specified by a `latexmath` expression instead of a simple name of a field. This appears to be the only member affected by the null-pointer issue, everything else seems to have a separate length field (or otherwise generate to invalid Rust).

**Comment by coffeenotfound** [comment]
Sadly I don't remember the exact problem why I thought an `Option<&'a [T]>` would be appropriate but looking over the vulkan docs again, the proposed fix seems good to me

**Comment by MarijnS95** [comment]
@coffeenotfound On the one hand that might improve API and intent, on the other it makes for an ambiguous case between `None` and `Some(&[])`, to the point where I'm not sure what would be most convenient. I'd generally have an assert against the length but `rasterizationSamples` may be set _after_ `pSampleMask` making that impossible :/

We could of course assert that, if `Some` is passed, the slice has a non-zero length.

**Comment by coffeenotfound** [comment]
@MarijnS95 For this specific case having len 0 result in a null pointer is fine since you can't have less than one sample and thus one element in the sample mask array -- at least right now

I guess it's about how low level ash wants to be... I'd personally prefer `Option<&'a [T]>` since then you're closer to the API (which could be important if some vulkan extension suddenly makes it valid to take a zero element sample mask slice)

**Comment by coffeenotfound** [comment]
Changing the function argument would be a breaking change though and while ash is still in major version zero I don't know how welcome those are, so here are my two cents:

0. Breaking: Change sample_mask's argument from `&'a [T]` to `Option<&'a [T]>`
1. Keep sample_mask with len 0 => null ptr semantics and add a second method `sample_mask_opt(self, Option<&'a [T]>)`
2. Change sample_mask's argument into `impl IntoOpt<&'a [T]>` with `trait IntoOpt<T> { fn into_option(self) -> Option<T>; } impl<T> IntoOpt<T> for T {...} impl<T> IntoOpt for Option<T> {...}`

My order of preference is 0 > 1 > 2

**Comment by Ralith** [comment]
We've got much larger breaking changes due soon, so I wouldn't worry about that.

> if some vulkan extension suddenly makes it valid to take a zero element sample mask slice

This seems really unlikely, though.

**Comment by MarijnS95** [comment]
> which could be important if some vulkan extension suddenly makes it valid to take a zero element sample mask slice

Vulkan has no idea about slice length - this is either passed as an explicit field in a struct or inherited from some other field as is the case with `PipelineMultisampleStateCreateInfo`.

> I don't quite get your concern over `Some(&[])` though. Isn't not being able to differentiate between `None` (null ptr) and `Some(&[])` (zero length slice) the very issue we're addressing here?

A valid pointer to memory that's length zero makes no sense anyway, as there's nothing to read/write there - it effectively becomes an identifier of some sort. In that sense `Some(&[])` and `None` would be completely ambiguous. Passing the former as valid pointer would make Vulkan read invalid memory because it expects `ceil(rasterizationSamples/32)` instead. If [VkSampleCountFlagBits](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSampleCountFlagBits.html) is believed `rasterizationSamples` is not allowed to go under `1` anyway meaning that it _always_ reads something from the pointer, being invalid memory in the `Some(&[])` if we don't assume that to be a null-pointer too.

Perhaps, since this function is overridden anyway we can explicitly document it.

> Changing the function argument would be a breaking change though and while ash is still in major version zero I don't know how welcome those are

No need to worry about that, semver allows breaking changes on most-significant version bumps - since our major is still `0` any minor version bump (which we do with every release regardless, and need to with a constant stream of API usability improvements and some minor semantic changes) counts as a most-significant version.
