### ISSUE TITLE
Implement Default for all vk types

### ISSUE THREAD

**Issue by farnoy** [MaikKlein/ash#27]
Hi, I'm not sure if this makes sense, but we could reduce verboseness by implementing Default trait for structs like `DeviceCreateInfo` and possibly many others. Filling in `s_type` and `p_next` is a hassle.

**Comment by MaikKlein** [comment]
I don't think it is that bad if you write some higher level abstraction, but I feel your pain. It was especially annoying when I wrote my first triangle example from scratch.

https://github.com/MaikKlein/ash/blob/3fa746380094721a96101a51a7b7682877d404cc/ash/src/vk.rs#L1200-L1211

So you would want to default initialize ptr to null and the other integer values to 0? 

Essentially you would want to write code like this (C++)

```
VkPipelineMultisampleStateCreateInfo multisampling = {};
multisampling.sampleShadingEnable = VK_FALSE;
multisampling.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
multisampling.minSampleShading = 1.0f; // Optional
multisampling.pSampleMask = nullptr; // Optional
multisampling.alphaToCoverageEnable = VK_FALSE; // Optional
multisampling.alphaToOneEnable = VK_FALSE; // Optional
```
Personally I actually liked that I had to initialize every struct explicitly. (for readability)

I don't see a problem with implementing `Default` though, but it is not a high priority for me. I guess it could be easily implemented with custom derive.

**Comment by mcoffin** [comment]
There is an issue with implementing `Default` for these types though. Some internal fields may not have sensible defaults. You should only implement `Default` for things that actually *do* have sensible defaults.

Eventually, you should be building a higher-level abstraction on top of those `(\w+)CreateInfo` structs anyways, since they're inherently unsafe memory-wise.
