### ISSUE TITLE
Direct symbol loading from libvulkan.so

### ISSUE THREAD

**Issue by kvark** [MaikKlein/ash#47]
We currently have a problem with gfx-rs [portability library](https://github.com/gfx-rs/portability): if running a Vulkan application linked to our portability so, the `gfx-backend-vulkan` ends up calling the function queries of the very same portability so, dying from stack overflow in recursion...
I wonder if this can be solved by Ash looking directly for `vkGetInstanceProcAddress` and friends in the native `libvulkan.so.1`:
> [kvark@carbon build]$ objdump /usr/lib64/libvulkan.so -T | grep vkGetInstance
0000000000025020 g    DF .text	00000000000013dc  Base        vkGetInstanceProcAddr

**Comment by MaikKlein** [comment]
@kvark 

So what you are saying is that, if you call anything inside https://github.com/gfx-rs/portability/blob/master/libportability/src/lib.rs with the vulkan backend, ash will give you the function pointer of the portability lib?

That seem very odd, I look at it a bit more closely later today, but I can give you a quick rundown what is happening inside ash right now.

I load the `vulkan.so` that is visible to the path https://github.com/MaikKlein/ash/blob/master/ash/src/entry.rs#L34 I actually wanted to make that explicit, but I couldn't because of Rust limitations which I think are gone now.

Inside this library I am going to look up `vkGetInstanceProcAddress` [link](https://github.com/MaikKlein/ash/blob/master/ash/src/vk.rs#L3859-L3864)

This happens here 
https://github.com/MaikKlein/ash/blob/master/ash/src/entry.rs#L167-L170

Then `Entry` uses `get_instance_proc_addr` to resolve the instance entry pointers.
https://github.com/MaikKlein/ash/blob/master/ash/src/version.rs#L37-L44

The same happens for instance function pointers
https://github.com/MaikKlein/ash/blob/master/ash/src/version.rs#L84-L91

For device function pointer I use get_device_proc_addr to avoid the indirection.
https://github.com/MaikKlein/ash/blob/master/ash/src/version.rs#L68-L78

**Comment by MaikKlein** [comment]
```
Starting program: /home/maik/src/VulkanSamples/dbuild/API-Samples/01-init_instance
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff761eb82 in portability_gfx::impls::gfxEnumerateInstanceExtensionProperties (pLayerName=<error reading variable: Cannot access memory at address 0x7fffff7feed8>,
    pPropertyCount=<error reading variable: Cannot access memory at address 0x7fffff7feee0>, pProperties=<error reading variable: Cannot access memory at address 0x7fffff7feee8>)
    at /home/maik/src/portability/libportability-gfx/src/impls.rs:341
341     pub extern "C" fn gfxEnumerateInstanceExtensionProperties(
```
This is currently what I get with gdb.

**Comment by kvark** [comment]
I'm getting the stack repeating this pattern:
```
#0  0x00007ffff7683362 in gfx_backend_vulkan::Instance::create (name=..., version=1)
    at /home/kvark/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/aaac641/src/backend/vulkan/src/lib.rs:130
#1  0x00007ffff75fd8fe in portability_gfx::impls::gfxCreateInstance (_pCreateInfo=0x7fffff800188, _pAllocator=0x0, 
    pInstance=0x7fffff7ff908) at /home/kvark/Code/gfx-eco/portability/libportability-gfx/src/impls.rs:45
#2  0x00007ffff75f1cd5 in portability::vkCreateInstance (pCreateInfo=0x7fffff800188, pAllocator=0x0, pInstance=0x7fffff7ff908)
    at libportability/src/lib.rs:17
#3  0x00007ffff769d575 in ash::vk::cmds::EntryFnV1_0::create_instance (self=0x1242a00, p_create_info=0x7fffff800188, p_allocator=0x0, 
    p_instance=0x7fffff7ff908) at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.21.1/src/vk.rs:3948
#4  0x00007ffff768d9ce in ash::entry::EntryV1_0::create_instance<ash::entry::Entry<ash::version::V1_0>> (self=0x12429f8, 
    create_info=0x7fffff800188, allocation_callbacks=...)
    at /home/kvark/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.21.1/src/entry.rs:87
#5  0x00007ffff768392e in gfx_backend_vulkan::Instance::create (name=..., version=1)
```

**Comment by MaikKlein** [comment]
I think this has been addressed now with the custom loader, feel free to reopen.
