### ISSUE TITLE
Cross platform example

### ISSUE THREAD

**Issue by NikNik77** [MaikKlein/ash#472]
Hello all

Is it possible to provide an initial config on the basis of ash API that can be compiled to 
1. windows 2. linux 3. macos 4. ios 5. android

It should draw a classical example of an  triangle by shaders.

Triangle should be redrawn than window resized, moved or opened

The structure of the project consists of:
1. The rust library that actually do all work
2. rust project is dependent on lib number 1. and can be compiled to all desktop platforms
3. java project is dependent on lib number 1. and can be compiled to android
4. swift project is dependent on lib number 1. and can be compiled to ios

**Comment by MarijnS95** [comment]
That's a lot to ask!

There's a `winit` example to cover most of your cases, but it's dated and it doesn't seem like anyone has the time to properly review #356 which updates to `winit` 0.24. This example should run as-is on Windows, Linux and Mac.

For Android no Java project is needed. Using `android-ndk-rs`, the `winit` support for it, and a few extra lines in `fn main()` the example compiles to a proper `NativeActivity`.

**Comment by NikNik77** [comment]
I have config for macos, linux and windows with gluitin.

The problem is in android. Something broken in android-ndk-rs. It make apk, that does not draw in window. So, I decided to try ash. In android I would use java that call ash by JNI. In this case it will be possible to use java fore some work within rust. Would you be able to provide an example how to call ash by JNI from android studio?

**Comment by MarijnS95** [comment]
> The problem is in android. Something broken in android-ndk-rs. It makes apk, that does not draw in window. 

Neither android-ndk-rs nor the underlying `NativeActivity` from Android draw anything. They provide a window handle from which a Vulkan swapchain (to be used with ash, see `ash-window`) or EGL display can be created that your Rust app subsequently renders to, just like for the other OS'es.

> So, I decided to try ash. In android I would use java that call ash by JNI. In this case it will be possible to use java fore some work within rust. Would you be able to provide an example how to call ash by JNI from android studio?

There are many different ways to set up a Rust application that runs cross-platform and uses Vulkan (or GL, as indicated by your glutin example?), and it entirely depends on the kind of application you intend to build, where most of the code lives (in Java or Rust?), and what code/architecture is already in place.

In that sense it is infeasible to build "some example Rust library for ash that can be called from JNI" since the Vulkan API is extensive.  Keep in mind that `NativeActivity` (exposed by android-ndk-rs) already provides all the necessary boilerplate to interop between Java (Android) and a native binary like those compiled from Rust - if you have a Rust rendering library with Ash it's quite uncommon to manually reinvent that all through JNI bindings.

**Comment by MarijnS95** [comment]
Closing this as stale and way out of scope for `ash`.
