### ISSUE TITLE
`AccelerationStructureInstanceKHR` is missing a builder

### ISSUE THREAD

**Issue by expenses** [MaikKlein/ash#474]
[`AccelerationStructureInstanceKHR`](https://docs.rs/ash/0.33.3+1.2.191/ash/vk/struct.AccelerationStructureInstanceKHR.html) is a nasty one to use without a builder as several fields are packed into one:

```c
// Provided by VK_KHR_acceleration_structure
typedef struct VkAccelerationStructureInstanceKHR {
    VkTransformMatrixKHR          transform;
    uint32_t                      instanceCustomIndex:24;
    uint32_t                      mask:8;
    uint32_t                      instanceShaderBindingTableRecordOffset:24;
    VkGeometryInstanceFlagsKHR    flags:8;
    uint64_t                      accelerationStructureReference;
} VkAccelerationStructure
```

See: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureInstanceKHR.html

If there's any way that I can help to fix this issue, please let me know :^)

**Comment by MarijnS95** [comment]
`AccelerationStructureInstanceKHR` is a manual structure because the generator cannot deal with bitfields yet, and it serves as a helper struct to fill a GPU buffer rather than being passed to the Vulkan CPU API as-is. The fields have already been collapsed into two `u32`'s, and you can easily fill them (on little-endian) with:

```rust
pub fn pack_24_8(low_24: u32, high_8: u8) -> u32 {
    (low_24 & 0x00ff_ffff) | (u32::from(high_8) << 24)
}
```

If you want we can expose this helper function inside an `impl AccelerationStructureInstanceKHR` to make it easier to construct, according to the layout rules described in https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAccelerationStructureInstanceKHR.html#_description.

**Comment by expenses** [comment]
@MarijnS95 Cool, I'm happy to write that `impl`, but which file should it be in?
