### ISSUE TITLE
Interleaving disappears in extension constants that are negative when running generator locally

### ISSUE THREAD

**Issue by i509VCB** [MaikKlein/ash#528]
Changes when running the generator using current master: https://gist.github.com/i509VCB/8eadb8b34f620d97299b74f80a927dde

I run the following, in the exact same way as github actions: `cargo run -p generator; cargo fmt -p ash`

rustup reports the following active toolchain, which is the latest stable toolchain:
> active toolchain
> ----------------
>
> stable-x86_64-unknown-linux-gnu (default)
> rustc 1.57.0 (f1edd0429 2021-11-29)

Interestingly this only occurs in the `extensions` and `feature_extensions` modules and only to the values that are negative?

Not sure if this is a bug with rustfmt or something else?

**Comment by i509VCB** [comment]
Hmm it might be quote? Given the raw output before fmt in one of the differing areas is:
```rust
impl Result { pub const ERROR_OUT_OF_POOL_MEMORY : Self = Self (- 1000069000) ; pub const ERROR_INVALID_EXTERNAL_HANDLE : Self = Self (- 1000072003) ;
```

**Comment by MarijnS95** [comment]
Maybe `cargo update`?

https://github.com/MaikKlein/ash/pull/486

**Comment by i509VCB** [comment]
Ah so it's the ancient lock file I have on my system.

I guess this is why I've been including my lock files with libraries work on for this reason.

**Comment by MarijnS95** [comment]
> including my lock files with libraries

Lock files only make sense for **binaries** (and give a false sense of security when locally build-testing library crates, theoretically they should work with `-Z minimal-versions` as well as the latest, otherwise dependency versions are underspecified): https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries.

Theoretically we could have bumped the minimum version of `syn` but since hardly anyone contributes to the generator I didn't bother.
