### ISSUE TITLE
Function pointer traits

### ISSUE THREAD

**Issue by MaikKlein** [MaikKlein/ash#80]
At the moment Ash roughly works like this:

Function pointers are loaded in groups. Instance, device and all the extensions. The idea is that if you don't need certain extensions that you don't need to load them.

Instance and device are grouped again in specific Vulkan versions. If you only need `1.0` function pointers, then you don't need to additionally load 1.1, 1.2, 1.3 etc. Further more they are implemented in traits which means that you can now statically know which function pointers you can use.

```
// requires at least a vk 1.1 context
fn allocate_something<Device: DeviceV1_1>(d: Device) {...} 
```
This might make it nicer for libraries to be written on top of Ash.

At the moment instance/device or extension creation fails if at least one function pointer fails to load. This sort of makes sense for instance and device because the core spec really should load, but it doesn't make sense for extensions as some function pointers only will load if another extension is also loaded. 

I think the best approach would be to be to allow function pointers to fail and initialize them to a static function that always panics. Conditional loading of specific function pointers in extensions is most likely too complicated for traits.

Another alternative would be to remove versioning and put all the function pointers in instance / device. The versioned traits could still be retained if this is wanted. The side effect is that we need to load everything, which means slightly longer initialization time, and more wasted space. Although it might not matter in practice and you are most likely boxing everything anyway.

Personally I like the way Ash works now, but I haven't heard any positive or negative arguments about the trait system and how Ash handles function pointers. I am sure this is the most subjective feature.

I don't personally think that anything, except that function pointers should be allowed to fail, needs to be changed, but I am always open to feedback.

**Comment by Ralith** [comment]
I don't think there's significant value in saving the storage/runtime for loading the extra pointers. There's probably something to be said for making it difficult to accidentally use functionality from a more recent version than intended, but traits aren't the only way this could be accomplished: you could require that a version be specified explicitly on instance create, either as a parameter to the constructor function or by having different constructor functions. Then function pointers for newer features would be defaulted to panicing impls rather than getting loaded even if the implementation supports them, ensuring that at least any tested codepaths won't have any such surprises on older hardware. This also has the benefit of reducing the amount of generic code, which simplifies APIs and speeds up compilation.

**Comment by MaikKlein** [comment]
Removed in 0.25
