### ISSUE TITLE
Split into ash and ash-sys

### ISSUE THREAD

**Issue by TimDiekmann** [MaikKlein/ash#91]
It would be very much more clean to split up ash into ash and ash-sys, where ash-sys only contains the generated files from the generator: https://github.com/MaikKlein/ash/issues/52#issuecomment-402036590

I'd do a PR when other PRs which affects *vk.rs* has been merged.

**Comment by MarijnS95** [comment]
With the closing of #93 (conflicting with lots of changes and refactors over the years) and the general conception that `ash` is already somewhat of a low-level, unopinionated crate [^1], I think we can close this issue too as being something not worth pursuing? Fwiw Vulkano switched to `ash` for its "sys" bindings.

For anyone interested in or referencing this issue: by all means voice your concerns if I'm judging this wrong. Since Ash seems to be the resident "standard" binding when it comes to Vulkan bindings [^2] we'd like to cater to most use cases, instead of forcing everyone to write their own generator + (`-sys`) crate, being type-incompatible with others at that. We can always reconsider splitting or refactoring.

[^1]: with the exception of not being a pure `-sys` crate: there are trait implementations, builders, function loaders, and hand-written extension helpers. These are all scheduled to be moved behind default-enabled features at some point.
[^2]: Alternative bindings, no matter how good they are, don't seem to take off.
